name: LittleRPG
main: littlegruz.arpeegee.ArpeegeeMain
version: 2.0.0

commands:
   ichoosemelee:
      description: Sets your class as melee
      usage: /ichoosemelee
   ichooseranged:
      description: Sets your class as ranged
      usage: /ichooseranged
   ichoosemagic:
      description: Makes it all complete
      usage: /ichoosemagic
   setquest:
      description: Prepares a quest to be set to a block
      usage: /setquest <quest_number>
   unsetquest:
      description: Prepares a quest to be removed from a block
      usage: /unsetquest
   displayquests:
      description: Displays all the quests loaded
      usage: /displayquests
   addrpgworld:
      description: Adds the current world to the list of worlds affected by the plugin
      usage: /addrpgworld
   removerpgworld:
      description: Removes the current world to the list of worlds affected by the plugin
      usage: /removerpgworld
   setrpgintro:
      description: Sets the introduction message for new players
      usage: /setrpgintro <message>
   setrpgreturn:
      description: Sets the introduction message for returning players
      usage: /setrpgreturn <message>
   createparty:
      description: Create a party
      usage: /createparty <party_name> [player_name] ...
   joinparty:
      description: Join a party
      usage: /joinparty <party_name>
   leaveparty:
      description: Leave current party
      usage: /leaveparty
   sendpartyinvite:
      description: Send invites for the party you are in
      usage: /sendpartyinvite <player_name> [player_name] ...
   removepartyinvite:
      description: Remove party invite for a player
      usage: /removepartyinvite <player_name> [player_name] ...
   party:
      description: Toggle party chat
      usage: /party

permissions:
   rpg.world:
      description: Adding or removing worlds where LittleRPG is active
      default: op
   rpg.questing:
      description: Setting up quests
      default: op
   rpg.text:
      description: Setting up joining text
      default: op
   rpg.begin:
      description: Choosing starting classes
      default: true
   rpg.party:
      description: Party creation/leaving/chatting
      default: true

softdepend: [Spout]
softdepend: [Multiverse-Core]
softdepend: [My Worlds]